DROP TABLE PRODUCT CASCADE CONSTRAINTS;
CREATE TABLE PRODUCT (
    PNO NUMBER(4) PRIMARY KEY,       -- 코드
    PNAME VARCHAR2(100) NOT NULL,    -- 물건명
    PSTOCK NUMBER(4) NOT NULL        -- 재고량
);
INSERT INTO PRODUCT VALUES (1, '공책', 3);
INSERT INTO PRODUCT VALUES (2, '볼펜', 10);
INSERT INTO PRODUCT VALUES (3, '지우개', 13);

SELECT * FROM PRODUCT WHERE PNAME='공책'; -- DAO QUERY
commit;