DROP TABLE BOOK;
CREATE TABLE BOOKKIND(
	BOOK_KIND NUMBER(3) PRIMARY KEY,
	KIND_NAME VARCHAR2(30),
	LOCATION VARCHAR2(50)
);
CREATE TABLE BOOK(
	BOOK_ID VARCHAR2(30) PRIMARY KEY,  -- 책ID
	BOOK_KIND NUMBER(3) REFERENCES BOOKKIND(BOOK_KIND), -- 책분류
	BOOK_TITLE VARCHAR2(60) NOT NULL, -- 책제목
	BOOK_PRICE NUMBER(6) NOT NULL,   -- 책가격
	BOOK_COUNT NUMBER(6) NOT NULL,   -- 책 재고 수량
	AUTHOR VARCHAR2(30) NOT NULL,    -- 저자
	PUBLISHING_COM VARCHAR2(30) NOT NULL, -- 출판사
	PUBLISHING_DATE DATE NOT NULL,   -- 출판일
	BOOK_IMAGE1 VARCHAR2(30) DEFAULT 'NOTHING.JPG' NOT NULL, -- 책 대표이미지
	BOOK_IMAGE2 VARCHAR2(30) DEFAULT 'noImg.png' NOT NULL,   -- 책 이미지
	BOOK_CONTENT VARCHAR2(4000),     -- 책소개
	BOOK_DISCOUNT NUMBER(3) DEFAULT 0,
	BOOK_RDATE DATE DEFAULT SYSDATE -- 등록일
);
SELECT * FROM BOOK;
DROP TABLE BOOK;
DROP TABLE BOOKKIND;
DROP SEQUENCE BOOK_SEQ;
CREATE SEQUENCE BOOK_SEQ MAXVALUE 9999999 NOCACHE NOCYCLE;
CREATE TABLE BOOK(
    bID NUMBER(7) PRIMARY KEY,    -- 책아이디
    bTITLE VARCHAR2(30) NOT NULL, -- 책제목
    bPRICE NUMBER(7) NOT NULL,    -- 책가격
    bIMAGE1 VARCHAR2(30) DEFAULT 'NOTHING.JPG' NOT NULL, -- 책대표이미지
    bIMAGE2 VARCHAR2(30) DEFAULT 'noImg.png' NOT NULL,   -- 책부가이미지
    bCONTENT VARCHAR2(4000),      -- 책설명
    bDISCOUNT NUMBER(3) NOT NULL, -- 할인율
    bRDATE DATE DEFAULT SYSDATE); -- 책 등록일
-- 책등록 
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bIMAGE2, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '이것은자바다',20000,'NOTHING.JPG','noImg.png','좋아',10);
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '이것은jsp다',21000,'NOTHING.JPG','뭐',15);
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE2, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '오라클',21000,'noImg.png','필요해',10);
INSERT INTO BOOK (bID, bTITLE, bPRICE, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '가나다',10000,'한글기초학습 짱',30);
-- 책목록
SELECT * FROM BOOK ORDER BY bRDATE DESC; -- 신착도서순으로 출력
-- 책목록(TOP-N) : 페이징
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM BOOK ORDER BY bRDATE DESC) A)
    WHERE RN BETWEEN 2 AND 3;
-- 등록된 책 갯수
SELECT COUNT(*) FROM BOOK;
-- bID로 책 가져오기
SELECT * FROM BOOK WHERE bID=3;