DROP TABLE FRIEND;
CREATE TABLE FRIEND (
    NO NUMBER(4),
    NAME VARCHAR2(20) NOT NULL,
    TEL VARCHAR2(20),
    PRIMARY KEY(NO),
    UNIQUE(TEL));
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ MAXVALUE 9999 NOCYCLE NOCACHE;
INSERT INTO FRIEND (NO, NAME, TEL) VALUES (FRIEND_SEQ.NEXTVAL, '홍길동','010-9999-9999');
SELECT * FROM FRIEND;
COMMIT;
-- 무료하신 분을 위한 검색 버튼 추가시
SELECT * FROM FRIEND WHERE NAME LIKE '%'||'길'||'%' AND TEL LIKE '%'||'8888'||'%';



