SELECT * FROM DEPT WHERE DEPTNO=30;
SELECT COUNT(*) "CNT" FROM DEPT WHERE DEPTNO=99;

INSERT INTO DEPT VALUES (60, 'MARKETING','SEOUL');
commit;
select * from dept;
UPDATE DEPT SET DNAME='MARKETING', LOC='SEOUL' WHERE DEPTNO=60;
DELETE FROM DEPT WHERE DEPTNO=70;
COMMIT;
SELECT * 
    FROM EMP 
    WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME='SALES');