-- DROP TABLE
DROP TABLE CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE CUS_LEVEL;
DROP SEQUENCE CUSTOMER_SEQ;
-- CREATE TABLE (CUS_LEVEL -> CUSTOMER )
CREATE TABLE CUS_LEVEL(
    LEVELNO NUMBER(1,0),
    LEVELNAME VARCHAR2(20),
    LOW NUMBER(10,0),
    HIGH NUMBER(10,0),
    PRIMARY KEY(LEVELNO));
CREATE SEQUENCE CUSTOMER_SEQ MAXVALUE 99999 NOCACHE NOCYCLE;
CREATE TABLE CUSTOMER(
    cID NUMBER(5,0) PRIMARY KEY,
    CTEL VARCHAR2(30) NOT NULL,
    CNAME VARCHAR2(50) NOT NULL,
    CPOINT NUMBER(10,0) DEFAULT 1000,
    CAMOUNT NUMBER(10,0) DEFAULT 0,
    LEVELNO NUMBER(1,0) DEFAULT 1 REFERENCES CUS_LEVEL(LEVELNO));
-- DATA INSERT (CUS_LEVEL(1:NORMAL,2:SILVER,3:GOLD,4:VIP,5:VVIP) ->CUSTOMER 1행추가)
------ 1  NORMAL 0~999999(100만원 미만) / 2  SILVER 100만원대
------ 3  GOLD   200만원대 / 4  VIP 300만원대 / 5 VVIP 400만원이상
INSERT INTO CUS_LEVEL VALUES (1, 'NORMAL', 0, 999999);
INSERT INTO CUS_LEVEL VALUES (2, 'SILVER', 1000000, 1999999);
INSERT INTO CUS_LEVEL VALUES (3, 'GOLD',   2000000, 2999999);
INSERT INTO CUS_LEVEL VALUES (4, 'VIP',    3000000, 3999999);
INSERT INTO CUS_LEVEL VALUES (5, 'VVIP',   4000000, 9999999999);
INSERT INTO CUSTOMER (cID, cTEL, cNAME) VALUES 
    (CUSTOMER_SEQ.NEXTVAL, '010-9999-9999','홍길동');
INSERT INTO CUSTOMER VALUES 
    (CUSTOMER_SEQ.NEXTVAL, '010-8888-9999','김길동');
COMMIT;
SELECT * FROM CUS_LEVEL;
SELECT * FROM CUSTOMER;
-- 프로그램에서 필요한 QUERY
-- 0. 레벨이름들 검색 - LEVALNAME
SELECT LEVELNAME FROM CUS_LEVEL;
-- 1. 폰뒤4자리(FULL) 검색 - CTEL, CNAME, CPOINT, CAMOUNT, LEVELNAME, 레벨업을위한쓸돈
SELECT CTEL, CNAME, CPOINT, CAMOUNT, LEVELNAME,  
        (SELECT HIGH-CAMOUNT+1 FROM CUSTOMER WHERE CID=C.CID AND LEVELNO !=5) LEVELUP
    FROM CUSTOMER C, CUS_LEVEL L
    WHERE C.LEVELNO=L.LEVELNO AND CTEL LIKE '%010-9999-9999'; -- "%"+textfield값
SELECT CID, CTEL, CNAME, CPOINT, CAMOUNT, LEVELNAME,
        (SELECT HIGH-CAMOUNT+1 FROM CUSTOMER WHERE CID=C.CID AND LEVELNO !=5) LEVELUP
    FROM CUSTOMER C, CUS_LEVEL L
    WHERE C.LEVELNO=L.LEVELNO AND CTEL LIKE '%'||'010-9999-9999'; -- 자바에서 쓸 SQL
-- 2. 고객이름검색 - CTEL, CNAME, CPOINT, CAMOUNT, LEVELNAME, 레벨업을위한쓸돈
SELECT CID, CTEL, CNAME, CPOINT, CAMOUNT, LEVELNAME, 
    (SELECT HIGH-CAMOUNT+1 FROM CUSTOMER WHERE cID=C.cID AND LEVELNO!=5) LEVELUP
    FROM CUSTOMER C, CUS_LEVEL L
    WHERE C.LEVELNO=L.LEVELNO AND cNAME='홍길동';
-- 3. 포인트로만 구매
UPDATE CUSTOMER SET cPOINT = cPOINT-10000 WHERE cID=2;
-- 4. 물품구매 (UPDATE문 2개, 1.포인트와누적구매금액조정 2.고객레벨조정)
UPDATE CUSTOMER SET cPOINT = cPOINT+1000000*0.05,
                    cAMOUNT = cAMOUNT + 1000000
            WHERE cID=1;
-- 2번 UPDATE
UPDATE CUSTOMER SET 
            LEVELNO = (SELECT L.LEVELNO FROM CUSTOMER C, CUS_LEVEL L
                         WHERE CAMOUNT BETWEEN LOW AND HIGH AND CID=1)
        WHERE CID=1;
SELECT * FROM CUSTOMER;
-- 1번과 2번을 합쳐
UPDATE CUSTOMER SET cPOINT = cPOINT+1000000*0.05,
                    cAMOUNT = cAMOUNT + 1000000,
                    LEVELNO = (SELECT L.LEVELNO FROM CUSTOMER C, CUS_LEVEL L
                         WHERE CAMOUNT+1000000 BETWEEN LOW AND HIGH AND CID=1)
            WHERE cID=1;   --- 자바에 쓸 SQL
SELECT * FROM CUSTOMER;
-- 5. 등급별출력 - CTEL, CNAME, CPOINT, CAMOUNT, LEVELNAME, 레벨업을위한쓸돈
SELECT CTEL, CNAME, CPOINT, CAMOUNT, LEVELNAME, 
    (SELECT HIGH-CAMOUNT+1 FROM CUSTOMER WHERE cID=C.cID AND LEVELNO!=5) LEVELUP
    FROM CUSTOMER C, CUS_LEVEL L
    WHERE C.LEVELNO=L.LEVELNO AND LEVELNAME='VVIP';
-- 6. 전체출력 - CTEL, CNAME, CPOINT, CAMOUNT, LEVELNAME, 레벨업을위한쓸돈
SELECT CTEL, CNAME, CPOINT, CAMOUNT, LEVELNAME, 
    (SELECT HIGH-CAMOUNT+1 FROM CUSTOMER WHERE cID=C.cID AND LEVELNO!=5) LEVELUP
    FROM CUSTOMER C, CUS_LEVEL L
    WHERE C.LEVELNO=L.LEVELNO
    ORDER BY CAMOUNT DESC;
-- 7. 회원가입 (고객전화와 고객이름은 입력받아 INSERT 할 예정)
INSERT INTO CUSTOMER (cID, cTEL, cNAME) VALUES 
    (CUSTOMER_SEQ.NEXTVAL, '010-9999-9999','홍길동');
-- 8. 번호수정 (UPDATE의 WHERE 절엔 CID로)
UPDATE CUSTOMER SET cTEL='010-7777-9999' WHERE cID=1;
-- 9. 회원탈퇴 (DELETE문)
DELETE FROM CUSTOMER WHERE cID=1;
ROLLBACK;
SELECT * FROM CUSTOMER;