DROP TABLE FILEBOARD;
DROP TABLE CUSTOMER;
DROP TABLE BOOK CASCADE CONSTRAINTS;
DROP SEQUENCE BOOK_SEQ;
CREATE SEQUENCE BOOK_SEQ MAXVALUE 9999999 NOCACHE NOCYCLE;
CREATE TABLE BOOK(
    bID NUMBER(7) PRIMARY KEY,    -- 책아이디
    bTITLE VARCHAR2(30) NOT NULL, -- 책제목
    bPRICE NUMBER(7) NOT NULL,    -- 책가격
    bIMAGE1 VARCHAR2(30) DEFAULT 'NOTHING.JPG' NOT NULL, -- 책대표이미지
    bIMAGE2 VARCHAR2(30) DEFAULT 'noImg.png' NOT NULL,   -- 책부가이미지
    bCONTENT VARCHAR2(4000),      -- 책설명
    bDISCOUNT NUMBER(3) NOT NULL, -- 할인율
    bRDATE DATE DEFAULT SYSDATE); -- 책 등록일
CREATE TABLE CUSTOMER(
	CID VARCHAR2(50) PRIMARY KEY,
	CPW VARCHAR2(50) NOT NULL,
	CNAME VARCHAR2(50) NOT NULL,
	CTEL VARCHAR2(50) NOT NULL,
	CEMAIL VARCHAR2(50),
	CADDRESS VARCHAR2(250),
    CGENDER VARCHAR2(10) NOT NULL,
	CBIRTH DATE NOT NULL,	
	CRDATE DATE DEFAULT SYSDATE
);
DROP SEQUENCE FILEBOARD_SEQ;
CREATE SEQUENCE FILEBOARD_SEQ MAXVALUE 9999999 NOCACHE NOCYCLE;
CREATE TABLE FILEBOARD(
    fNUM     NUMBER(7) PRIMARY KEY,
    cID      VARCHAR2(50) REFERENCES CUSTOMER(cID),
    fSUBJECT VARCHAR2(250) NOT NULL,
    fCONTENT VARCHAR2(4000),
    fFILENAME VARCHAR2(50),
    fPW      VARCHAR2(50) NOT NULL,
    fHIT     NUMBER(7) DEFAULT 0 NOT NULL,
    fREF     NUMBER(7) NOT NULL,
    fRE_STEP NUMBER(7) NOT NULL,
    fRE_LEVEL NUMBER(7) NOT NULL,
    fIP      VARCHAR2(50) NOT NULL,
    fRDATE   DATE DEFAULT SYSDATE NOT NULL);