-- V. 그룹함수 : SUM, AVG, MIN, MAX, COUNT, STDDEV, VARIANCE
SELECT SUM(SAL) FROM EMP;
SELECT DEPTNO, SUM(SAL) FROM EMP GROUP BY DEPTNO; -- DEPNO 별로 SAL을 SUM한 결과
SELECT DEPTNO, SUM(SAL) 
    FROM EMP 
    WHERE ENAME!='SMITH'
    GROUP BY DEPTNO
    HAVING SUM(SAL)>9000
    ORDER BY DEPTNO;
-- EMP테이블의 평균SAL
SELECT ROUND(AVG(SAL),2) FROM EMP;
SELECT COUNT(*) FROM EMP; -- EMP 테이블의 행수
SELECT SUM(SAL)/COUNT(*), AVG(SAL) FROM EMP;
SELECT SUM(COMM) FROM EMP; -- 그룹함수일 경우 NULL값은 제외하고 계산
SELECT SUM(COMM)/COUNT(COMM), AVG(COMM) FROM EMP;
SELECT COUNT(COMM) FROM EMP;
SELECT VARIANCE(SAL) 분산, STDDEV(SAL) 표준편차 FROM EMP;
SELECT DEPTNO, AVG(SAL), STDDEV(SAL) FROM EMP GROUP BY DEPTNO
    ORDER BY AVG(SAL);
SELECT DEPTNO, MAX(SAL) FROM EMP GROUP BY DEPTNO;
SELECT COUNT(JOB) FROM EMP; -- JOB 데이터가 있는 행수
SELECT JOB FROM EMP;
SELECT DISTINCT JOB FROM EMP;
SELECT COUNT(DISTINCT JOB) FROM EMP; -- 중복된 데이터를 제거한 행수
-- 탄탄다지기
-- 가장 최근에 입사한 직원의 입사일과 가장 최초에 입사한 직원의 입사일 출력
SELECT MIN(SAL), MAX(SAL) FROM EMP;
SELECT MIN(ENAME), MAX(ENAME) FROM EMP;
SELECT MIN(HIREDATE) "최초입사일", MAX(HIREDATE) "최근입사일" FROM EMP;
-- 최근입사일, 최근입사일부터오늘까지일수, 최초입사일, 최초입사일부터오늘까지일수
SELECT MAX(HIREDATE), TO_CHAR(TRUNC(SYSDATE-MAX(HIREDATE)), '99,999'), 
    MIN(HIREDATE), TRUNC(SYSDATE-MIN(HIREDATE)) FROM EMP;
-- 10번 부서 소속의 사원의 평균 급여
SELECT AVG(SAL) FROM EMP WHERE DEPTNO=10;
-- 10번 부서 소속의 COMM(상여금)을 받는 사원의 수는?
SELECT COUNT(COMM) FROM EMP WHERE DEPTNO=10; -- DEPTNO가 10번 인 직원
-- AVG(SAL)이 2000이상 ( 그룹함수에 대한 조건은 WHERE 절이 아니고 HAVING절에 )
SELECT DEPTNO, AVG(SAL) FROM EMP GROUP BY DEPTNO HAVING AVG(SAL)>2000; 
-- 부서번호별 평균급여, 급여최소값, 급여최대값
SELECT DEPTNO, AVG(SAL), MIN(SAL), MAX(SAL) FROM EMP GROUP BY DEPTNO;
-- 부서명별 평균급여를 출력(부서명 ABCD순으로 출력)
SELECT DNAME, AVG(SAL)
    FROM EMP E, DEPT D
    WHERE E.DEPTNO=D.DEPTNO
    GROUP BY DNAME
    ORDER BY DNAME;
-- 부서번호별 사원수와 상여금을 받는 사원수
SELECT DEPTNO, COUNT(*), COUNT(COMM) FROM EMP GROUP BY DEPTNO;
-- 부서이름별 사원수와 상여금 받는 사원수
SELECT DNAME 부서, COUNT(*), COUNT(COMM) FROM EMP E, DEPT D
    WHERE D.DEPTNO=E.DEPTNO 
    GROUP BY DNAME
    ORDER BY 부서;
-- GROUP BY 필드1, 필드2
SELECT DEPTNO, AVG(SAL) FROM EMP GROUP BY DEPTNO;
SELECT DEPTNO, JOB, AVG(SAL) FROM EMP GROUP BY DEPTNO, JOB ORDER BY DEPTNO;
-- GROUP BY 절에 필드가 2개 일 때 가독성을 높이기 위해 DECODE
SELECT DEPTNO, DECODE(JOB, 'CLERK', SAL, 0) CLERK,
               DECODE(JOB, 'MANAGER', SAL, 0) MANAGER,
               DECODE(JOB, 'PRESIDENT', SAL, 0) PRESIDENT,
               DECODE(JOB, 'ANALYST', SAL, 0) ANALYST,
               DECODE(JOB, 'SALESMAN', SAL, 0) SALESMAN FROM EMP;
               
SELECT DEPTNO, SUM(DECODE(JOB, 'CLERK', SAL, 0)) CLERK,
               SUM(DECODE(JOB, 'MANAGER', SAL, 0)) MANAGER,
               SUM(DECODE(JOB, 'PRESIDENT', SAL, 0)) PRESIDENT,
               SUM(DECODE(JOB, 'ANALYST', SAL, 0)) ANALYST,
               SUM(DECODE(JOB, 'SALESMAN', SAL, 0)) SALESMAN,
               SUM(SAL) "부서별소계"
               FROM EMP 
               GROUP BY ROLLUP(DEPTNO);
SELECT DEPTNO, JOB, SUM(SAL) FROM EMP GROUP BY DEPTNO, JOB;
SELECT DEPTNO, SUM(SAL) FROM EMP GROUP BY ROLLUP(DEPTNO);
SELECT DEPTNO, AVG(SAL) FROM EMP GROUP BY ROLLUP(DEPTNO);

SELECT JOB, DEPTNO, AVG(SAL) FROM EMP GROUP BY JOB, DEPTNO;
SELECT JOB, DEPTNO, AVG(SAL) FROM EMP GROUP BY ROLLUP(JOB, DEPTNO);
-- 위의 결과를 피벗테이블로 바꿔보세요
-- 좌측(JOB) 우측(DEPTNO)별 AVG(SAL) 소계포함
--      	10번부서	20번부서	30번부서	소계
--ANALYST	xxx	    xxx	    xxx	     xxx
--CLERK	    xxx	    xxx	    xxx      xxx
--MANAGER	xxx	    xxx	    xxx	     xxx
--PRESIDENT	xxx	    xxx	    xxx	     xxx
--SALESMAN	xxx	    xxx	    xxx	     xxx
--소계	    xxx	    xxx	    xxx	     xxx
SELECT JOB, DECODE(DEPTNO, 10, SAL) "10번부서",
            DECODE(DEPTNO, 20, SAL) "20번부서",
            DECODE(DEPTNO, 30, SAL) "30번부서"
        FROM EMP;
SELECT JOB, ROUND(AVG(DECODE(DEPTNO, 10, SAL))) "10번부서",
            ROUND(AVG(DECODE(DEPTNO, 20, SAL))) "20번부서",
            ROUND(AVG(DECODE(DEPTNO, 30, SAL))) "30번부서",
            ROUND(AVG(SAL)) "소계"
        FROM EMP GROUP BY ROLLUP(JOB);
-- 부서번호별 평균급여출력(평균급여가 2000이상인 그룹만 출력)
SELECT DEPTNO, AVG(SAL) FROM EMP GROUP BY DEPTNO HAVING AVG(SAL)>=2000;
-- 부서번호별 최대급여 출력
SELECT DEPTNO, MAX(SAL) FROM EMP GROUP BY DEPTNO;
-- 부서번호별 부서번호, 최대급여, 사원이름 => 서브쿼리











-- ★<셤 연습문제>

-- 1. 사원 테이블에서 인원수,최대 급여,최소 급여,급여의 합을 계산하여 출력
SELECT COUNT(*), MAX(SAL), MIN(SAL), SUM(SAL) FROM EMP;
-- 2. 사원테이블에서 업무별 인원수를 구하여 출력하는 SELECT 문장을 작성하여라.
SELECT JOB, COUNT(*) FROM EMP GROUP BY JOB;
--- 3. 사원테이블에서 최고 급여와 최소 급여의 차이는 얼마인가 출력하는 SELECT문장을 작성하여라.
SELECT MAX(SAL) - MIN(SAL) FROM EMP;
-- 4. 각 부서별로 인원수, 급여 평균, 최저 급여, 최고 급여, 급여의 합을 출력하되 급여의 합이 많은 순으로 출력하라.
SELECT DEPTNO, COUNT(*), AVG(SAL), MIN(SAL), MAX(SAL), SUM(SAL) SUM_SAL 
    FROM EMP 
    GROUP BY DEPTNO 
    ORDER BY SUM_SAL DESC;
SELECT DEPTNO, COUNT(*), AVG(SAL), MIN(SAL), MAX(SAL), SUM(SAL) 
    FROM EMP
    GROUP BY DEPTNO 
    ORDER BY SUM(SAL) DESC;
SELECT DNAME, COUNT(*), AVG(SAL), MIN(SAL), MAX(SAL), SUM(SAL)
    FROM EMP E, DEPT D
    WHERE E.DEPTNO=D.DEPTNO
    GROUP BY DNAME
    ORDER BY SUM(SAL) DESC;
-- 5. 부서별, 업무별 그룹하여 결과를 부서번호, 업무, 인원수, 급여의 평균, 급여의 합을 
    --구하여 출력하라(출력결과는 부서번호, 업무순으로 오름차순 정렬)
SELECT DEPTNO, JOB, COUNT(*), AVG(SAL), SUM(SAL) 
    FROM EMP GROUP BY DEPTNO, JOB ORDER BY DEPTNO, JOB; -- 부서번호, 업무별
    
SELECT DNAME, JOB, COUNT(*), AVG(SAL), SUM(SAL)
    FROM EMP E, DEPT D
    WHERE E.DEPTNO=D.DEPTNO
    GROUP BY DNAME, JOB ORDER BY DNAME, JOB; -- 부서이름, 업무별
    
-- 6. 업무별, 부서별 그룹하여 결과를  업무, 부서번호, 인원수, 급여의 평균, 급여의 합을 구하여 
-- 출력하라.(출력결과는 업무순, 부서번호 순 오름차순 정렬)
SELECT JOB, DEPTNO, COUNT(*), AVG(SAL), SUM(SAL) 
    FROM EMP GROUP BY JOB, DEPTNO ORDER BY JOB, DEPTNO;
    
-- 7~10번 HAVING 절    
--7. 사원수가 5명이상 넘는 부서번호와 사원수를 출력하시오.
SELECT DEPTNO, COUNT (*) 
  FROM EMP GROUP BY DEPTNO HAVING COUNT(*)>5; --그룹(group by)에 대한 조건은 having절에

-- 8. 사원수가 5명이상 넘는 부서명과 사원수를 출력하시오
SELECT DNAME, COUNT(SAL) FROM EMP E, DEPT D
    	WHERE E.DEPTNO=D.DEPTNO GROUP BY DNAME HAVING COUNT(*)>=5;

--9. 사원 테이블에서 업무별 급여의 평균이 3000이상인 업무에 대해서 업무명, 평균 급여, 
--급여의 합을 구하여 출력하라
SELECT JOB, AVG(SAL), SUM(SAL) FROM EMP GROUP BY JOB HAVING AVG(SAL)>=3000;

--10. 사원테이블에서 급여합이 5000을 초과하는 각 업무에 대해서 업무와 급여합계를 출력하라 
        --단, 급여 합계로 내림차순 정렬하라.
SELECT JOB, SUM(SAL) SUMSAL
    FROM EMP GROUP BY JOB HAVING SUM(SAL)>5000 ORDER BY SUMSAL DESC;
SELECT JOB, SUM(SAL)
    FROM EMP GROUP BY JOB HAVING SUM(SAL)>5000 ORDER BY SUM(SAL) DESC;

--11. 부서별 급여평균, 부서별 급여합계, 부서별 최소급여를 출력하라.
SELECT DNAME, AVG(SAL), MAX(SAL), MIN(SAL) 
    FROM EMP E, DEPT D
    WHERE E.DEPTNO=D.DEPTNO GROUP BY DNAME; -- 부서이름별
    
SELECT DEPTNO, AVG(SAL), MAX(SAL), MIN(SAL) FROM EMP GROUP BY DEPTNO; -- 부서번호별
    
--12. 위의 11번을 수정하여, 부서별 급여평균 최대치, 부서별 급여합의 최대치, 
            --부서별 최소급여의 최대치를 출력하라.
SELECT MAX(AVG(SAL)), MAX(MAX(SAL)), MAX(MIN(SAL)) FROM EMP GROUP BY DEPTNO;

--13. 사원 테이블에서 아래의 결과를 출력하는 SELECT 문장을 작성하여라.(년도별 연봉합)
--   H_YEAR	COUNT(*)	MIN(SAL)	MAX(SAL)	AVG(SAL)	SUM(SAL)
--		80	  1		    800		    800		    800		    800
--		81	 10		    950		    5000		2282.5		22825
--		82	  2		    1300		3000		2150		4300
--		83	  1		    1100		1100		1100		1100
SELECT TO_CHAR(HIREDATE,'YY') H_YEAR, COUNT(*), MIN(SAL), MAX(SAL), AVG(SAL), 
        SUM(SAL) 
    FROM EMP GROUP BY TO_CHAR(HIREDATE,'YY') ORDER BY H_YEAR;

SELECT SUBSTR(EXTRACT(YEAR FROM HIREDATE),3,2) H_YEAR, 
        COUNT(*), MIN(SAL), MAX(SAL), AVG(SAL), SUM(SAL) 
    FROM EMP GROUP BY SUBSTR(EXTRACT(YEAR FROM HIREDATE),3,2) ORDER BY H_YEAR;

-- 14.  사원테이블에서 아래의 결과를 출력하는 SELECT 문 작성
-- TOTAL	1980	1981	1982	1983
--  14		  1	     10	      2	      1
SELECT EXTRACT(YEAR FROM HIREDATE), COUNT(*)  
    FROM EMP GROUP BY ROLLUP(EXTRACT(YEAR FROM HIREDATE));
SELECT DECODE(EXTRACT(YEAR FROM HIREDATE), '1980', 1) "1980",
       DECODE(EXTRACT(YEAR FROM HIREDATE), '1981', 1) "1981",
       DECODE(EXTRACT(YEAR FROM HIREDATE), '1982', 1) "1982",
       DECODE(EXTRACT(YEAR FROM HIREDATE), '1983', 1) "1983" FROM EMP;
SELECT COUNT(*) TOTAL, 
       COUNT(DECODE(EXTRACT(YEAR FROM HIREDATE), '1980', 1)) "1980",
       COUNT(DECODE(EXTRACT(YEAR FROM HIREDATE), '1981', 1)) "1981",
       COUNT(DECODE(EXTRACT(YEAR FROM HIREDATE), '1982', 1)) "1982",
       COUNT(DECODE(EXTRACT(YEAR FROM HIREDATE), '1983', 1)) "1983" FROM EMP;
SELECT COUNT(*) TOTAL,
       SUM(DECODE(EXTRACT(YEAR FROM HIREDATE), '1980', 1)) "1980",
       SUM(DECODE(EXTRACT(YEAR FROM HIREDATE), '1981', 1)) "1981",
       SUM(DECODE(EXTRACT(YEAR FROM HIREDATE), '1982', 1)) "1982",
       SUM(DECODE(EXTRACT(YEAR FROM HIREDATE), '1983', 1)) "1983" FROM EMP;
--15. 사원테이블에서 아래의 결과를 출력하는 SELECT 문 작성(JOB 순으로 오름차순 정렬)
-- JOB별, DEPTNO별 SUM(SAL)
--JOB		DEPTNO10	DEPTNO20	DEPTNO30     TOTAL
--ANALYST	     0		   6000		    0		6000
--CLERK		  1300		   1900		  950		4150
--….
--SALESMAN	      0	 		0	 5600		 5600
SELECT JOB, DECODE(DEPTNO, 10, SAL, 0) "DEPTNO10",  -- 이전 단계 SQL
    DECODE(DEPTNO, 20, SAL, 0) "DEPTNO20",
    DECODE(DEPTNO, 30, SAL, 0) "DEPTNO30"
     FROM EMP ORDER BY JOB;
SELECT JOB, SUM(DECODE(DEPTNO, 10, SAL,0)) "DEPTNO 10",
            SUM(DECODE(DEPTNO, 20, SAL,0)) "DEPTNO 20",
            SUM(DECODE(DEPTNO, 30, SAL,0)) "DEPTNO 30",
            SUM(SAL) "TOTAL"
		FROM EMP GROUP BY JOB ORDER BY JOB;
        
--16. 사원테이블에서 최대급여, 최소급여, 전체급여합, 평균을 구하시오
SELECT MAX(SAL), MIN(SAL), SUM(SAL), AVG(SAL) FROM EMP;

--17. 사원테이블에서 부서별 인원수를 구하시오
SELECT DEPTNO, COUNT(*) FROM EMP GROUP BY DEPTNO;
SELECT DNAME, COUNT(*) FROM EMP E, DEPT D 
        WHERE E.DEPTNO=D.DEPTNO GROUP BY DNAME ORDER BY DNAME;
        
--18. 사원 테이블에서 부서별 인원수가 6명이상인 부서코드를 구하시오
SELECT DEPTNO, COUNT(*) FROM EMP GROUP BY DEPTNO HAVING COUNT(*)>=6;

--19. 사원테이블에서 다음과 같은 결과가 나오게 하시오
--DNAME               CLERK    MANAGER     PRESIDENT    ANALYST   SALESMAN
--ACCOUNTING            1300       2450       5000          0          0
--RESEARCH              1900       2975          0       6000          0
--SALES                 950        2850          0          0       5600
SELECT DNAME, SUM(DECODE(JOB, 'CLERK', SAL, 0)) CLERK,
              SUM(DECODE(JOB, 'MANAGER', SAL,0)) MANAGER,
              SUM(DECODE(JOB, 'PRESIDENT', SAL,0)) PRESIDENT,
              SUM(DECODE(JOB, 'ANALYST', SAL,0)) ANALYST,
              SUM(DECODE(JOB, 'SALESMAN', SAL,0)) SALESMAN
              FROM EMP E, DEPT D
              WHERE E.DEPTNO=D.DEPTNO
              GROUP BY DNAME;
              
--20.  사원테이블에서 급여가 높은 순서대로 등수를 부여하여 다음과 같은 결과가 나오게 하시오. 
-- (힌트 self join, group by, count사용)
--ENAME	    등수
--________________________
--KING		1
--SCOTT		2
--……
SELECT E1.ENAME, COUNT(E2.ENAME)+1 등수
    FROM EMP E1, EMP E2
    WHERE E1.SAL<E2.SAL(+)
    GROUP BY E1.ENAME
    ORDER BY 등수;
SELECT ENAME, RANK() OVER(ORDER BY SAL DESC) RANK,
              DENSE_RANK() OVER (ORDER BY SAL DESC) D_RANK,
              ROW_NUMBER() OVER (ORDER BY SAL DESC) R_RANK FROM EMP;