-- 조회속도를 높이기 위한 인덱스
DROP TABLE EMP01;
CREATE TABLE EMP01 AS SELECT * FROM EMP;
INSERT INTO EMP01 SELECT * FROM EMP01; -- 30
SELECT COUNT(*) FROM EMP01;
INSERT INTO EMP01 SELECT * FROM EMP01; -- 2번 실행하면 100개 가량
INSERT INTO EMP01 (EMPNO, ENAME) VALUES (1111, 'HONG'); -- 데이터의 1%가 HONG
INSERT INTO EMP01 SELECT * FROM EMP01; -- 11번 실행하여 20만개 ROW
SELECT TO_CHAR(COUNT(*),'999,999') FROM EMP01;
SELECT * FROM USER_INDEXES; -- EMP01테이블과 관련된 인덱스는 없음 확인
SELECT * FROM EMP01 WHERE ENAME='HONG'; -- 0.006초
CREATE INDEX IDX_EMP01_ENAME ON EMP01(ENAME); -- 인덱스 생성
SELECT * FROM EMP01 WHERE ENAME='HONG'; -- 0.004초
INSERT INTO EMP01 SELECT * FROM EMP01;
DROP INDEX IDX_EMP01_ENAME;
INSERT INTO EMP01 SELECT * FROM EMP01;






